version: '2'
services:
    microserapplicationdemo1-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/MicroserApplicationDemo1/mongodb/:/data/db/
